name: teslo_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  formz: ^0.8.0
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - assets/google_fonts/montserrat_alternates/
    - .env
